# Generated by Django 4.2.6 on 2023-11-24 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_auf', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
