# Generated by Django 4.2.6 on 2023-12-02 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_credit_linked_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credit',
            old_name='term_months',
            new_name='term_years',
        ),
    ]
