# Generated by Django 4.2.6 on 2023-12-02 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_rename_term_months_credit_term_years'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='linked_card',
        ),
    ]
