# Generated by Django 4.2.6 on 2023-12-03 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='from account')),
                ('number', models.CharField(default='random', max_length=16)),
                ('expiry_date', models.DateField(default='admin check')),
                ('expiry_years', models.PositiveIntegerField(default=0)),
                ('cvv', models.CharField(default='random', max_length=3)),
                ('card_type', models.CharField(choices=[('debit', 'Дебетовая'), ('credit', 'Кредитная')], default='debit', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('linked_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_account.account')),
            ],
        ),
    ]
