# Generated by Django 4.2.6 on 2023-11-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.CharField(default='random', max_length=3),
        ),
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.CharField(default='random', max_length=16, unique=True),
        ),
    ]
