# Generated by Django 4.2.6 on 2023-11-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_expiry_years_alter_card_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expiry_years',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
