# Generated by Django 4.2.6 on 2023-12-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_card_expiry_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('debit', 'Дебетовая'), ('credit', 'Кредитная')], default='debit', max_length=10),
        ),
    ]
