# Generated by Django 4.2.6 on 2023-12-03 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_alter_history_content_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
